background = #0b0712
foreground = #eee8f7
background-opacity = 0.96
cursor-color = #c49cff
selection-background = #49315f
selection-foreground = #fff8ff

palette = 0=#0b0712
palette = 1=#b54865
palette = 2=#5d9a7a
palette = 3=#c49a4b
palette = 4=#7155a2
palette = 5=#a85d9f
palette = 6=#668fb5
palette = 7=#d9cfdf
palette = 8=#695b75
palette = 9=#dc718c
palette = 10=#82c29b
palette = 11=#e5bc6b
palette = 12=#9a7bd2
palette = 13=#d183c7
palette = 14=#8eb9db
palette = 15=#fff8ff
