background = #160e16
foreground = #f7ead7
background-opacity = 0.96
cursor-color = #e79a55
selection-background = #633524
selection-foreground = #fff8ed

palette = 0=#160e16
palette = 1=#ae3f32
palette = 2=#687e50
palette = 3=#c49a3f
palette = 4=#586c85
palette = 5=#a65772
palette = 6=#61898a
palette = 7=#e6d6c0
palette = 8=#79645e
palette = 9=#db6045
palette = 10=#8da46b
palette = 11=#e2ba61
palette = 12=#7d93aa
palette = 13=#ce7893
palette = 14=#84b0ad
palette = 15=#fff8ed
