background = #101820
foreground = #e8f3f5
background-opacity = 0.96
cursor-color = #70e1e7
selection-background = #275968
selection-foreground = #f5fdff

palette = 0=#101820
palette = 1=#bd4b2b
palette = 2=#5e9b72
palette = 3=#d99b32
palette = 4=#4a8fa8
palette = 5=#a97891
palette = 6=#42c9db
palette = 7=#dce7e7
palette = 8=#60777d
palette = 9=#f0784f
palette = 10=#7dc992
palette = 11=#ffd166
palette = 12=#74c8dc
palette = 13=#d49ab8
palette = 14=#8be8ee
palette = 15=#f7ffff
