-- Generated by zenwolf-theme-build. Edit profile.json, not this file.
hl.config({
    general = {
        border_size = 1,
        col = {
            active_border = "rgba(4fd5dfe6)",
            inactive_border = "rgba(426b7599)",
        },
    },
    decoration = {
        rounding = 2,
    },
    misc = {
        background_color = "rgb(101820)",
    },
})

return {
    overlay_rounding = 3,
    overlay_border_size = 1,
}
