background = #090817
foreground = #f4efff
background-opacity = 0.96
cursor-color = #56d5e5
selection-background = #253f5e
selection-foreground = #f8fdff

palette = 0=#090817
palette = 1=#b93346
palette = 2=#3e9b50
palette = 3=#c99716
palette = 4=#307fc4
palette = 5=#b14ac7
palette = 6=#28c9df
palette = 7=#ded8e9
palette = 8=#675c7a
palette = 9=#ee5267
palette = 10=#63c76e
palette = 11=#f1bd34
palette = 12=#5ca6e5
palette = 13=#e072ed
palette = 14=#70e6f2
palette = 15=#fff9ff
