background = #f4e8d5
foreground = #2d2925
background-opacity = 0.97
cursor-color = #326d82
selection-background = #72b0c7
selection-foreground = #2d2925

palette = 0=#2d2925
palette = 1=#a84422
palette = 2=#246b43
palette = 3=#805813
palette = 4=#326d82
palette = 5=#85667d
palette = 6=#327c82
palette = 7=#dfcfb7
palette = 8=#6f6457
palette = 9=#cf6845
palette = 10=#4b9166
palette = 11=#ad7d2c
palette = 12=#72b0c7
palette = 13=#a47f9a
palette = 14=#7ccacf
palette = 15=#fffaf1
