-- Generated by zenwolf-theme-build. Edit profile.json, not this file.
hl.config({
    general = {
        border_size = 1,
        col = {
            active_border = "rgba(326d82d9)",
            inactive_border = "rgba(b8aa94a6)",
        },
    },
    decoration = {
        rounding = 2,
    },
    misc = {
        background_color = "rgb(f4e8d5)",
    },
})

return {
    overlay_rounding = 3,
    overlay_border_size = 1,
}
