background = #0c0c10
foreground = #cdd0cb
background-opacity = 1
cursor-color = #a1a99e
selection-background = #5e706c
selection-foreground = #f8fafc

palette = 0=#161719
palette = 1=#ef4444
palette = 2=#22c55e
palette = 3=#f59e0b
palette = 4=#5e706c
palette = 5=#927aa8
palette = 6=#7a8b83
palette = 7=#cdd0cb
palette = 8=#606762
palette = 9=#f87171
palette = 10=#4ade80
palette = 11=#facc15
palette = 12=#99a39a
palette = 13=#c4a7e7
palette = 14=#dce3dc
palette = 15=#f9fafb
