background = #170e0a
foreground = #f3dfc1
background-opacity = 0.96
cursor-color = #d89a3c
selection-background = #415c50
selection-foreground = #fff8e9

palette = 0=#170e0a
palette = 1=#a9323f
palette = 2=#637f6f
palette = 3=#bd7d25
palette = 4=#5c7481
palette = 5=#89616f
palette = 6=#6f928a
palette = 7=#dfc9a9
palette = 8=#746455
palette = 9=#d0525d
palette = 10=#86a993
palette = 11=#dfa24a
palette = 12=#8099a6
palette = 13=#b48091
palette = 14=#96b9ad
palette = 15=#fff4dc
