background = #0a060f
foreground = #afdbc9
background-opacity = 1
cursor-color = #51a192
selection-background = #4d7985
selection-foreground = #f8fafc

palette = 0=#15111a
palette = 1=#ef4444
palette = 2=#22c55e
palette = 3=#f59e0b
palette = 4=#4d7985
palette = 5=#9b72cf
palette = 6=#51a192
palette = 7=#afdbc9
palette = 8=#4e6568
palette = 9=#f87171
palette = 10=#4ade80
palette = 11=#facc15
palette = 12=#75aeb8
palette = 13=#c4a7e7
palette = 14=#9adfd0
palette = 15=#f9fafb
