-- Generated by zenwolf-theme-build. Edit profile.json, not this file.
hl.config({
    general = {
        border_size = 1,
        col = {
            active_border = "rgba(51a192ff)",
            inactive_border = "rgba(51a1928c)",
        },
    },
    decoration = {
        rounding = 0,
    },
    misc = {
        background_color = "rgb(0a060f)",
    },
})

return {
    overlay_rounding = 12,
    overlay_border_size = 1,
}
