background = #0b1021
foreground = #f1e6cf
background-opacity = 0.96
cursor-color = #d4ad68
selection-background = #414968
selection-foreground = #fff9e8

palette = 0=#0b1021
palette = 1=#a94c4c
palette = 2=#5f816a
palette = 3=#c79a54
palette = 4=#4f6f9e
palette = 5=#86638c
palette = 6=#5d8b9b
palette = 7=#ddd4c3
palette = 8=#5e6477
palette = 9=#d16e68
palette = 10=#82a88a
palette = 11=#e1bd7b
palette = 12=#7694c2
palette = 13=#ab82ae
palette = 14=#82b2bd
palette = 15=#fff9e8
